name: icona
description: "Packages for Iconamoon icons"
version: 1.0.0+1
repository: https://github.com/ping5721/icona

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.5.0+1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    # Bold
    - assets/bold/arrow/
    - assets/bold/communication/
    - assets/bold/ecommerce/
    - assets/bold/emojis/
    - assets/bold/files/
    - assets/bold/general/
    - assets/bold/interface/
    - assets/bold/math/
    - assets/bold/media/
    
    # Regular
    - assets/regular/arrow/
    - assets/regular/communication/
    - assets/regular/ecommerce/
    - assets/regular/emojis/
    - assets/regular/files/
    - assets/regular/general/
    - assets/regular/interface/
    - assets/regular/math/
    - assets/regular/media/

    # Color
    - assets/color/arrow/
    - assets/color/communication/
    - assets/color/ecommerce/
    - assets/color/emojis/
    - assets/color/files/
    - assets/color/general/
    - assets/color/interface/
    - assets/color/math/
    - assets/color/media/

    # Cute
    - assets/cute/arrow/
    - assets/cute/communication/
    - assets/cute/ecommerce/
    - assets/cute/emojis/
    - assets/cute/files/
    - assets/cute/general/
    - assets/cute/interface/
    - assets/cute/math/
    - assets/cute/media/

    # Duotone
    - assets/duotone/arrow/
    - assets/duotone/communication/
    - assets/duotone/ecommerce/
    - assets/duotone/emojis/
    - assets/duotone/files/
    - assets/duotone/general/
    - assets/duotone/interface/
    - assets/duotone/math/
    - assets/duotone/media/

    # Fill
    - assets/fill/arrow/
    - assets/fill/communication/
    - assets/fill/ecommerce/
    - assets/fill/emojis/
    - assets/fill/files/
    - assets/fill/general/
    - assets/fill/interface/
    - assets/fill/math/
    - assets/fill/media/

    # Light
    - assets/light/arrow/
    - assets/light/communication/
    - assets/light/ecommerce/
    - assets/light/emojis/
    - assets/light/files/
    - assets/light/general/
    - assets/light/interface/
    - assets/light/math/
    - assets/light/media/

    # Thin
    - assets/thin/arrow/
    - assets/thin/communication/
    - assets/thin/ecommerce/
    - assets/thin/emojis/
    - assets/thin/files/
    - assets/thin/general/
    - assets/thin/interface/
    - assets/thin/math/
    - assets/thin/media/
    
flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    outputs: 
      class_name: Iconamoon
      package_parameter_enabled: true 
      directory_path_enabled: true