name: icona
description: "Packages for Iconamoon icons"
version: 1.0.0+1
repository: https://github.com/ping5721/icona

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.5.0+1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/bold/
    - assets/color/
    - assets/cute/
    - assets/duotone/
    - assets/fill/
    - assets/light/
    - assets/regular/
    - assets/thin/
  
    
flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    outputs: 
      class_name: Iconamoon
      package_parameter_enabled: true 
      directory_path_enabled: true